geometry/urls.py
from django.urls import path

from .views import create_person, triangle, update_person

app_name = 'geometry'
urlpatterns = [
        path('', triangle, name='triangle'),
        path('person/', create_person, name='create_person'),
        path('<int:pk>/person/', update_person, name='update_person')
    ]

hm3/urls.py
from django.contrib import admin
from django.urls import include, path

from geometry.views import triangle

urlpatterns = [
    path('admin/', admin.site.urls),
    path('triangle/', include('geometry.urls')),
]

catalog/models.py
from django.db import models


class City(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title


class Product(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Client(models.Model):
    name = models.CharField(max_length=25)
    offer = models.ManyToManyField(Product)
    actions = models.ForeignKey(City, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Executor(models.Model):
    city = models.OneToOneField(City, on_delete=models.CASCADE, primary_key=True)
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

geometry/models.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=35)
    email = models.EmailField(max_length=100)


class Logs(models.Model):
    class Method(models.TextChoices):
        POST = 'P', 'POST'
        GET = 'G', 'GET'

    path = models.CharField(max_length=120)
    method = models.CharField(max_length=10, choices=Method.choices)
    time = models.DateTimeField(auto_now_add=True)

geometry/forms.py
from django import forms

from .models import Person


class HypoForm(forms.Form):
    catet = forms.IntegerField(label='Enter first catet', min_value=1)
    catet2 = forms.IntegerField(label='Enter second catet', min_value=1)


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'email']

catalog/views.py
from django.shortcuts import render

# Create your views here.

geometry/views.py
from django.shortcuts import get_object_or_404, redirect, render

from .forms import HypoForm, PersonForm
from .models import Person


def triangle(request):
    form = HypoForm()
    if 'submit' in request.GET:
        form = HypoForm(request.GET)
        if form.is_valid():
            gip = pow(int(form.cleaned_data['catet']), 2) + pow(int(form.cleaned_data['catet2']), 2)
            return render(request, 'hypotenuse.html', {'form': form, 'gip': gip})
    return render(request, 'hypotenuse.html', {'form': form})


def create_person(request):
    form = PersonForm()
    if request.method == "POST":
        form = PersonForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('geometry:create_person')
    else:
        return render(request, 'Person.html', {'form': form})
    return render(request, 'Person.html', {'form': form})


def update_person(request, pk):
    person = get_object_or_404(Person, pk=pk)
    if request.method == 'POST':
        form = PersonForm(request.POST, instance=person)
        if form.is_valid():
            obj = form.save()
            return redirect('geometry:update_person', obj.id)
        return render(request, 'Person_update.html', {'form': form})
    else:
        form = PersonForm(instance=person)
    return render(request, 'Person_update.html', {'form': form})

templates/Person.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'geometry:create_person' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>

</body>
</html>

templates/Person_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'geometry:update_person' form.instance.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"  value="update">
    </form>
</body>
</html>

templates/hypotenuse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'geometry:triangle' %}" method="get">
    {{ form.as_p }}
    <input type="submit" name="submit" value="OK">
    <p>Гипотенуза равна {{ gip }}</p>
</form>
</body>
</html>

templates/person.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'geometry:create_person' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>

</body>
</html>

templates/person_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'geometry:update_person' form.instance.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"  value="update">
    </form>
</body>
</html>